# Makefile — Pebble Time 2 Hello World in Embedded Swift (Swift 6.3+)
# Targets:
#   make              — compile Swift → .o + C → .o (link needs real Pebble SDK)
#   make header       — emit the Swift-generated C header (PebbleApp-Swift.h)
#   make symbols      — show exported symbols from Swift object
#   make diagnostics  — type-check with EmbeddedRestrictions warnings visible
#   make clean        — remove build artefacts

# ── Toolchain ─────────────────────────────────────────────────────────────────
SWIFTC   := swiftc
CC       := arm-none-eabi-gcc
NM       := arm-none-eabi-nm

# ── Target: SF32LB52J high-performance core (Cortex-M33) ──────────────────────
TARGET_TRIPLE := armv8m.main-none-none-eabi
MCPU          := cortex-m33
MFPU          := fpv5-sp-d16
MFLOAT_ABI   := hard

# ── Paths ─────────────────────────────────────────────────────────────────────
BUILD_DIR     := build
SRC_SWIFT     := src/swift/PebbleSDK.swift src/swift/App.swift
SRC_C         := src/c/main.c
INCLUDE_DIR   := include
SWIFT_HEADER  := $(BUILD_DIR)/PebbleApp-Swift.h   # generated by @c (SE-0495)

PEBBLE_SDK_PATH ?= $(HOME)/.pebble-sdk/SDKs/current/sdk-core
ARM_SYSROOT     := /Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/arm-none-eabi

# ── Swift flags ───────────────────────────────────────────────────────────────
# Swift 6.3: -enable-experimental-feature Embedded is required
# -Xfrontend -disable-reflection-metadata: saves ~1-2 KB; keep until LLDB
# support for Embedded DWARF is your primary debug path (it is, for Pebble).
SWIFT_FLAGS := \
  -enable-experimental-feature Embedded \
  -target $(TARGET_TRIPLE) \
  -Xcc -mcpu=$(MCPU) \
  -Xcc -mthumb \
  -Xcc -mfpu=$(MFPU) \
  -Xcc -mfloat-abi=$(MFLOAT_ABI) \
  -Xcc -ffreestanding \
  -Xcc -I$(ARM_SYSROOT)/include \
  -Xcc -I$(INCLUDE_DIR) \
  -I $(INCLUDE_DIR) \
  -wmo \
  -O \
  -Xfrontend -disable-reflection-metadata \
  -Xfrontend -disable-stack-protector \
  -module-name PebbleApp

# ── C flags ───────────────────────────────────────────────────────────────────
CFLAGS := \
  -mcpu=$(MCPU) \
  -mthumb \
  -mfpu=$(MFPU) \
  -mfloat-abi=$(MFLOAT_ABI) \
  -ffreestanding \
  -ffunction-sections \
  -fdata-sections \
  -Os \
  -I$(INCLUDE_DIR)

# ── Rules ─────────────────────────────────────────────────────────────────────
.PHONY: all header symbols diagnostics clean

all: $(BUILD_DIR)/swift_app.o $(BUILD_DIR)/main.o

# 1. Compile Swift sources → ARM object + emit generated C header
#    Swift 6.3: -emit-objc-header-path emits declarations for all @c-annotated symbols.
#    main.c can then #include "build/PebbleApp-Swift.h" for validated signatures.
$(BUILD_DIR)/swift_app.o: $(SRC_SWIFT) $(INCLUDE_DIR)/module.modulemap | $(BUILD_DIR)
	@echo "▶ Compiling Embedded Swift (6.3+) → $@"
	$(SWIFTC) $(SWIFT_FLAGS) \
	  -emit-objc-header-path $(SWIFT_HEADER) \
	  -c $(SRC_SWIFT) \
	  -o $@
	@echo "✓ Swift compiled  |  generated header: $(SWIFT_HEADER)"

# 2. Compile C entry point (optionally includes generated Swift header)
$(BUILD_DIR)/main.o: $(SRC_C) | $(BUILD_DIR)
	@echo "▶ Compiling C → $@"
	$(CC) $(CFLAGS) -c $< -o $@
	@echo "✓ C compiled"

# Emit ONLY the generated Swift→C header (no object file)
header: | $(BUILD_DIR)
	$(SWIFTC) $(SWIFT_FLAGS) \
	  -emit-objc-header-path $(SWIFT_HEADER) \
	  -typecheck $(SRC_SWIFT)
	@echo "✓ Generated header written to $(SWIFT_HEADER)"
	@cat $(SWIFT_HEADER)

# Show exported ARM symbols from the Swift object
symbols: $(BUILD_DIR)/swift_app.o
	@echo "── Symbols in $< ──"
	$(NM) --defined-only $(BUILD_DIR)/swift_app.o | sort

# Type-check with EmbeddedRestrictions warnings explicitly surfaced
# (they're on by default in Swift 6.3 Embedded; this just makes them visible)
diagnostics:
	$(SWIFTC) $(SWIFT_FLAGS) \
	  -Wwarning EmbeddedRestrictions \
	  -typecheck $(SRC_SWIFT)

$(BUILD_DIR):
	mkdir -p $@

clean:
	rm -rf $(BUILD_DIR)
	@echo "✓ Cleaned"
