#pragma once
#include <stdint.h>
#include "gtypes.h"

// --- GBitmap (raster image loaded from a resource) ---
// Opaque handle; the real Pebble SDK owns the layout. Swift imports this as
// an OpaquePointer. Bitmaps are created from "bitmap"/"png" resources declared
// in package.json and drawn into a GContext during a layer update proc.
typedef struct GBitmap GBitmap;

GBitmap *gbitmap_create_with_resource(uint32_t resource_id);
void     gbitmap_destroy(GBitmap *bitmap);
GRect    gbitmap_get_bounds(const GBitmap *bitmap);

// --- Compositing ---
// PNGs carry an alpha channel; GCompOpSet honours it so the transparent areas
// of the Swift logo let the background show through.
typedef enum GCompOp {
    GCompOpAssign         = 0,
    GCompOpAssignInverted = 1,
    GCompOpOr             = 2,
    GCompOpAnd            = 3,
    GCompOpClear          = 4,
    GCompOpSet            = 5,
} GCompOp;

void graphics_context_set_compositing_mode(GContext ctx, GCompOp mode);
void graphics_draw_bitmap_in_rect(GContext ctx, const GBitmap *bitmap, GRect rect);

// --- Resource id bridge ---
// Resource ids (RESOURCE_ID_*) are generated by the Pebble build into the real
// SDK headers, which the C sources see but our Swift module does not. This tiny
// accessor (defined in src/c/resources.c) hands the id to Swift.
uint32_t swift_resource_id_swift_logo(void);
