#pragma once
#include "gtypes.h"

// System font keys
#define FONT_KEY_GOTHIC_14            "RESOURCE_ID_GOTHIC_14"
#define FONT_KEY_GOTHIC_14_BOLD       "RESOURCE_ID_GOTHIC_14_BOLD"
#define FONT_KEY_GOTHIC_18            "RESOURCE_ID_GOTHIC_18"
#define FONT_KEY_GOTHIC_18_BOLD       "RESOURCE_ID_GOTHIC_18_BOLD"
#define FONT_KEY_GOTHIC_24            "RESOURCE_ID_GOTHIC_24"
#define FONT_KEY_GOTHIC_24_BOLD       "RESOURCE_ID_GOTHIC_24_BOLD"
#define FONT_KEY_GOTHIC_28            "RESOURCE_ID_GOTHIC_28"
#define FONT_KEY_GOTHIC_28_BOLD       "RESOURCE_ID_GOTHIC_28_BOLD"
#define FONT_KEY_BITHAM_30_BLACK      "RESOURCE_ID_BITHAM_30_BLACK"
#define FONT_KEY_BITHAM_42_BOLD       "RESOURCE_ID_BITHAM_42_BOLD"
#define FONT_KEY_BITHAM_42_LIGHT      "RESOURCE_ID_BITHAM_42_LIGHT"
#define FONT_KEY_ROBOTO_BOLD_SUBSET_49 "RESOURCE_ID_ROBOTO_BOLD_SUBSET_49"
#define FONT_KEY_LECO_42_NUMBERS       "RESOURCE_ID_LECO_42_NUMBERS"

GFont fonts_get_system_font(const char *font_key);
